controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

traitement_commande:
    path: /traitement
    controller: App\Controller\LandingPageController::traitement
    methods: [GET, POST]

cgv:
    path: /cgv
    controller: App\Controller\LandingPageController::afficherCGV
